# Generated by Django 3.2.2 on 2021-05-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoappnew', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mytodonew',
            new_name='Mytodo',
        ),
    ]
